# platform :ios, '15.0'

target 'beeconvert' do

  use_frameworks!

  pod 'GCDWebServer'
  pod 'Google-Mobile-Ads-SDK'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless target.respond_to?(:resources_build_phase)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end

    target.resources_build_phase.files.each do |file|
      if file.display_name.include?("_CodeSignature")
        file.remove_from_project
      end
    end

  end
end
